### ISSUE TITLE
Améliorer l'affichage des descriptions de clubs

### ISSUE THREAD

**Issue by arnaudvergnet** [ClubInfoInsaT/application-amicale#12]
L'éditeur de texte de l'Amicale permet d'ajouter des effets comme du texte en gros, en couleurs, des images sur ligne de texte et autres. Ces effets ne sont pas correctement interprétés par le parseur HTML, ce qui peut amener à une perte d'information (image ou texte manquant).

**Comment by Paulao17** [comment]
Issue resolved since `5.2.4`. Also resolves duplicate #45.

https://github.com/ClubInfoInsaT/application-amicale/compare/81263da...b20de47
