### ISSUE TITLE
Crash lors de l'ouverture de l'appli sur planex

### ISSUE THREAD

**Issue by arnaudvergnet** [ClubInfoInsaT/application-amicale#20]
Pour certains utilisateurs, ouvrir l'application avec planex par défaut donne un crash.

Arrive sur 2 utilisateurs Android 9, et un 6.0.1.

Mettre à jour les dépendances sur react-native, hermes ou la webview devraient sûrement corriger le problème.

**Comment by ignyx** [comment]
This issue still haunts me
