### ISSUE TITLE
Faire fonctionner les tests unitaires

### ISSUE THREAD

**Issue by arnaudvergnet** [ClubInfoInsaT/application-amicale#22]
Remettre à jour et faire marcher les tests unitaires

**Comment by Paulao17** [comment]
See https://github.com/ClubInfoInsaT/application-amicale/commit/541c00255895713f926e41c7cca11aa2d0ef91f4 for connection manager changes

**Comment by Paulao17** [comment]
fixed as of a75eab2ea28443fb80db94d1fc96b130617fb137
