### ISSUE TITLE
Mettre à jour l'endpoint d'API du CROUS

### ISSUE THREAD

**Issue by Paulao17** [ClubInfoInsaT/application-amicale#30]
Il se pourrait que le menu du RU soit indisponible car l'endpoint du menu du RU aurait changé.

**Comment by Shinyhero36** [comment]
J'ai décompilé l'appli CROUS Mobile et dans le code source de l'app, l'endpoint est le même que celui utilisé par le serveur de l'application amicale.

```java
public static final String WEBSERVICES_URL = "https://webservices-v2.crous-mobile.fr/ws/v1";

[...]

public ApiQuery(int i, String str) {
    super(i, Constants.WEBSERVICES_URL + str);
    setRetryPolicy(new DefaultRetryPolicy(POLICY_TIME_OUT_MS, 3, 1.2f));
}

[...]

public class GetMenus extends ApiQuery {
    public static final String CACHE_ID = "menus.json";
    public static final String RESPONSE_EVENT = "GetMenusResponse";
    private int regionId;
    private int restaurantId;
    private Timer timeout;

    public GetMenus(int i, int i2) {
        super(0, "/regions/" + i + "/restaurants/" + i2 + "/menus/");
        this.regionId = i;
        this.restaurantId = i2;
        setResponseParserType(JsonMenuListParser.PARSER_TYPE);
        setContentResponseType(RESPONSE_EVENT);
    }
   [...]
}
```

Je ne pense pas que l'API est changé d'endpoint parce que y'a encore des restos du CROUS qui fonctionnent (liste non complète):
- [Cafétéria Mini'Gem](https://webservices-v2.crous-mobile.fr/ws/v1/regions/2/restaurants/32/menus)
- [Restaurant Sanital](https://webservices-v2.crous-mobile.fr/ws/v1/regions/2/restaurants/33/menus)
- [Resto U' Envt](https://webservices-v2.crous-mobile.fr/ws/v1/regions/5/restaurants/119/menus)
- [Cafétéria Le Tropical](https://webservices-v2.crous-mobile.fr/ws/v1/regions/6/restaurants/136/menus)

**Comment by Paulao17** [comment]
Le [menu de la cafet](https://webservices-v2.crous-mobile.fr/ws/v1/regions/5/restaurants/1617/menus) est lui aussi indisponible

**Comment by Paulao17** [comment]
The [endpoint](https://webservices-v2.crous-mobile.fr/ws/v1/regions/5/restaurants/114/menus) is now up again, hence the RU menu is working again.
