### ISSUE TITLE
Problème d'affichage de "mes clubs" : n'en affiche qu'un 

### ISSUE THREAD

**Issue by Mstrdav** [ClubInfoInsaT/application-amicale#44]
# Rapport de bug

## Comportement attendu

Campus devrait afficher tous mes rôles de gestions de clubs

## Comportement actuel

Je ne vois que le premier : Club Jeux, celui que j'ai rejoins il y a un an. Les plus récents ne sont pas affichés.

## Étapes pour reproduire le problème

1. Ouvrir campus
2. Être connecté avec son compte amicale
3. Aller dans profil, scroller en bas

# Contexte

* Type de téléphone (Android/iOS) : Android
* Version du système : 12
* Version de l'application Campus : la dernière
* Modèle de téléphone : Google Pixel 5a

![image](https://user-images.githubusercontent.com/52855284/179201561-d8b88329-af1c-44b7-bbd9-b1930937f5f7.png)

**Comment by Paulao17** [comment]
Possibly a backend issue on the Amicale's website. Will be looked into, thanks for the report !

**Comment by ignyx** [comment]
Clubs are being redone, to work with the new Amicale API
