### ISSUE TITLE
Proxywash crash application

### ISSUE THREAD

**Issue by andreapefe** [ClubInfoInsaT/application-amicale#57]
# Rapport de bug

## Comportement attendu
Je clique sur proxywash depuis l'accueil de l'app.
Les machines disponibles et occupés s'affichent sur l'écran

## Comportement actuel
Je clique sur proxywash depuis l'accueil de l'app.
L'application se ferme et un message de "Application ne répond plus" s'affiche me forçant à fermer l'application. 

## Étapes pour reproduire le problème
1. Ouvrir application
2. Sur la page d'accueil Clickez sur icône en bas de proxywash 
3. Appli crash

# Contexte
* Type de téléphone (Android/iOS) : samsung A30 avec Android 11
* Version du système : Kernel : 4.4.177-22825772 / 
* Version de l'application Campus : 5.2.4
* Autres informations que tu juges utiles :
J'ai essayé avec d'autres téléphones et ce problème n'existe pas.
J'ai déjà reinstallé l'appli, actualisé mon tél et le reinitialisé. 
Mon appli est en espagnol ? 
# Détails

**Comment by Paulao17** [comment]
Hello ! Merci pour ton issue détaillée ! 

Est-ce que le problème persiste lorsque la langue de ton tél est en Français ou Anglais ?

![image](https://user-images.githubusercontent.com/23584745/196518005-d4ec2335-d998-4471-b9f2-fcad9246e95f.png)

Dev notes : If yes, is likely an issue with `react-native-time-ago` and `src/components/Lists/Proxiwash/ProxiwashListHeader.tsx`

**Comment by andreapefe** [comment]
Salut,
Le problème est résolu si je met mon téléphone en Français. Je n'ai pas testé pour l'anglais mais ça doit être pareil.

**Comment by Paulao17** [comment]
Le problème devrait être résolu dans la prochaine release. Si tu veux, tu peux installer la Beta depuis Google Play Store. Une version Beta (`5.2.7`) avec le fix devrait paraître dans la journée. Est-ce que ça résout le problème ?

**Comment by Paulao17** [comment]
Assumed resolved.
