### ISSUE TITLE
L'app campus n'affiche plus les bonnes info de Proxiwash

### ISSUE THREAD

**Issue by Shinyhero36** [ClubInfoInsaT/application-amicale#76]
# Rapport de bug

## Comportement attendu

Les informations de l'application devraient être *"identiques"* à celles sur [le site de Proxiwash](https://beta.proxiwash.com/fr/laverie?code=cf4f39)

## Comportement actuel

Les infos affichées sur l'app ne sont pas les même que celle sur le site de Proxiwash

## Solution possible

Mettre à jour le scraper [JSON data](https://api.cogedia.com/laveries/cf4f39/machines?machinestype=0&machinesvue=laverie&version=2)

## Étapes pour reproduire le problème

1. Ouvrir l'app
2. Se rendre dans l'onglet Proxiwash

# Contexte

Essaie de compléter le plus d'info possible.

* Type de téléphone (Android/iOS) : Android
* Version du système : Android 13 
* Version de l'application Campus : 5.3.3
* Autres informations que tu juges utiles : Aucune

# Détails

Si jamais tu veux dire des choses en plus c'est ici.

**Comment by baptistereb** [comment]
suggestion de solution à essayer : résoudre le probleme en remplaçant la constante "PROXIWASH_ENDPOINT" dans le fichier src/constants/Urls.tsx
